Aid CTAD to work around module problems.
Something about the layout of WebKit confuses clang modules when they encounter RefPtr<T>.
This seems to show up in two different ways:

* Errors are produced for any header file stating simply
   RefPtr ptr = <some expression returning a raw pointer>
  These errors say that no deduction is possible to work out the type of RefPtr,
  because none of the user-specified nor implicit deduction guides apply.

  /Users/adrian_taylor/WebKit/OpenSource/WebKitBuild/Debug/usr/local/include/wtf/RefPtr.h:49:19: note: candidate template ignored: couldn't infer template argument '_PtrTraits'
    ALWAYS_INLINE RefPtr(T* ptr) : m_ptr(RefDerefTraits::refIfNotNull(ptr)) { }
                  ^
  /Users/adrian_taylor/WebKit/OpenSource/WebKitBuild/Debug/usr/local/include/wtf/RefPtr.h:49:19: note: implicit deduction guide declared as 'template <typename T, typename _PtrTraits = RawPtrTraits<T>, typename _RefDerefTraits = DefaultRefDerefTraits<T>> RefPtr(T *ptr) -> RefPtr<T, type-parameter-0-1, type-parameter-0-2>'
    ALWAYS_INLINE RefPtr(T* ptr) : m_ptr(RefDerefTraits::refIfNotNull(ptr)) { }
                  ^
* Where std::variants include a RefPtr, they also can't work because
  the std module is unable to work out the constructibility of RefPtr, per the
  following errors:

  EmitSwiftModule normal arm64e (in target 'WebKit' from project 'WebKit')
    cd /Users/xxx/WebKit/OpenSource/Source/WebKit

  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.Internal.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:28:2: note: in module 'std_math_h' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.Internal.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:28:
   ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.Internal.sdk/usr/include/c++/v1/math.h:361:8: note: in module 'std_core' imported from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.Internal.sdk/usr/include/c++/v1/math.h:361:
         ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.Internal.sdk/usr/include/c++/v1/__type_traits/is_constructible.h:34:38: error: missing '#include "wtf/RefPtr.h"'; 'RefPtr' must be defined before it is used
      : public integral_constant<bool, __is_constructible(_Tp, __add_lvalue_reference_t<const _Tp>)> {};
                                       ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.Internal.sdk/usr/include/c++/v1/__type_traits/is_constructible.h:38:76: note: in instantiation of template class 'std::is_copy_constructible<WTF::RefPtr<WebCore::FragmentedSharedBuffer>>' requested here
  _LIBCPP_NO_SPECIALIZATIONS inline constexpr bool is_copy_constructible_v = is_copy_constructible<_Tp>::value;
                                                                             ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.Internal.sdk/usr/include/c++/v1/variant:1160:41: note: in instantiation of variable template specialization 'std::is_copy_constructible_v<WTF::RefPtr<WebCore::FragmentedSharedBuffer>>' requested here
      : private __sfinae_ctor_base< __all<is_copy_constructible_v<_Types>...>::value,
                                          ^
  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX16.0.Internal.sdk/usr/include/c++/v1/variant:1159:84: note: in instantiation of template class 'std::variant<WebCore::ShareableResourceHandle, WTF::RefPtr<WebCore::FragmentedSharedBuffer>>' requested here
  class _LIBCPP_TEMPLATE_VIS _LIBCPP_DECLSPEC_EMPTY_BASES _LIBCPP_NO_SPECIALIZATIONS variant
                                                                                     ^
  /Users/xxx/WebKit/OpenSource/WebKitBuild/Debug/usr/local/include/wtf/RefPtr.h:37:7: note: definition here is not reachable
  class RefPtr {
        ^

I think this problem probably arises because the arrangement of WebKit's
headers results in RefPtr being spread across two clang modules. We have
three modules: WebKit, WebKit_Private and WebKit_Internal. I suspect
RefPtr is in one of those, while either RefPtr's forward declaration
(in wtf/Forward.h), and/or RawPtrTraits and DefaultRefDerefTraits
are in a different module.

These problems, though still mysterious, can be worked around by providing an
explicit template argument deduction guide. That's what this commit does.